### ISSUE TITLE
NPE in QualifiedNameBuilder when opening vala file

### ISSUE THREAD

**Issue by gregorej** [gregorej/vala-intellij-plugin#32]
```
java.lang.NullPointerException
	at org.intellij.vala.psi.impl.QualifiedNameBuilder.from(QualifiedNameBuilder.java:108)
	at org.intellij.vala.psi.impl.ValaPsiImplUtil.getQName(ValaPsiImplUtil.java:93)
	at org.intellij.vala.psi.impl.ValaCreationMethodDeclarationImpl.getQName(ValaCreationMethodDeclarationImpl.java:80)
	at org.intellij.vala.parser.ValaCreationMethodDeclarationStubElementType.createStub(ValaCreationMethodDeclarationStubElementType.java:30)
	at org.intellij.vala.parser.ValaCreationMethodDeclarationStubElementType.createStub(ValaCreationMethodDeclarationStubElementType.java:18)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:60)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
	at com.intellij.psi.impl.source.PsiFileImpl.calcStubTree(PsiFileImpl.java:987)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:62)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:40)
	at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:273)
	at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:264)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:264)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:237)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:95)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:226)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:216)
	at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java:39)
	at org.intellij.vala.psi.index.DeclarationQualifiedNameIndex.get(DeclarationQualifiedNameIndex.java:42)
	at org.intellij.vala.reference.ValaTypeReference.resolve(ValaTypeReference.java:42)
	at org.intellij.vala.reference.ValaTypeReference.resolveInImportedNamespaces(ValaTypeReference.java:48)
	at org.intellij.vala.reference.ValaTypeReference.resolve(ValaTypeReference.java:36)
	at org.intellij.vala.psi.impl.ValaPsiImplUtil.getTypeDescriptor(ValaPsiImplUtil.java:202)
	at org.intellij.vala.psi.impl.ValaPsiImplUtil.getTypeDescriptor(ValaPsiImplUtil.java:195)
	at org.intellij.vala.psi.impl.ValaTypeImpl.getTypeDescriptor(ValaTypeImpl.java:37)
	at org.intellij.vala.psi.impl.ValaPsiImplUtil.getSuperTypeDeclarations(ValaPsiImplUtil.java:220)
	at org.intellij.vala.psi.impl.ValaPsiImplUtil.getSuperTypeDeclarations(ValaPsiImplUtil.java:210)
	at org.intellij.vala.psi.impl.ValaClassDeclarationImpl.getSuperTypeDeclarations(ValaClassDeclarationImpl.java:96)
	at org.intellij.vala.reference.ValaFieldReference.getMatchingMethodDeclarationInSuperClasses(ValaFieldReference.java:70)
	at org.intellij.vala.reference.ValaFieldReference.resolveAsClassFieldReference(ValaFieldReference.java:64)
	at org.intellij.vala.reference.ValaFieldReference.resolveAsThisClassFieldReference(ValaFieldReference.java:51)
	at org.intellij.vala.reference.ValaFieldReference.resolve(ValaFieldReference.java:35)
	at org.intellij.vala.ValaAnnotator.isClassFieldAccess(ValaAnnotator.java:23)
	at org.intellij.vala.ValaAnnotator.annotate(ValaAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:160)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$5.run(GeneralHighlightingPass.java:313)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:399)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:405)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:402)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:405)
	at com.intellij.codeInsight.daemon.impl.RefCountHolder.analyze(RefCountHolder.java:321)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:175)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:402)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:390)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:230)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1143)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)```

**Comment by gregorej** [comment]
Most probably caused by creation_method in struct_declaration (previously creation_method was only in class)
